### PR TITLE
Updated instructions for VS 2013 Express and renamed folder to match README

### PR DESCRIPTION
**Pull request by nurtext**
Like the title says…

### CODE REVIEW

**Comment by Jalle19** [comment]
Can you do this PR against the upstream repository instead (opdenkamp/xbmc-pvr-addons)? If it gets accepted there I can rebase this fork.

**Comment by nurtext** [comment]
@Jalle19 Sure, could you please tell me on how to do this without re-forking from opdenkamp's repo?

**Comment by Jalle19** [comment]
Try checking out his master branch and then cherry pick this commit, then create a new pull request.

**Comment by nurtext** [comment]
@Jalle19 Still figuring out how to checkout another repo into my forked one :D

**Comment by Jalle19** [comment]
git remote add opdenkamp <url>
git checkout opdenkamp/master

Something like that.

**Comment by nurtext** [comment]
@Jalle19 stupid me… of course. Well… had a long day in the office. Sorry mate…

**Comment by Jalle19** [comment]
Github ate my placeholder, the last thing on the first line should be a URL to the remote repository.

**Comment by nurtext** [comment]
I can't get it to work… will remove my repo and patch the files over at opdenkamp.

**Comment by Jalle19** [comment]
Thanks for taking the time.

**Comment by Jalle19** [comment]
I'm closing this for now. LIke I said, this needs to be done against the upstream repository.

**Pull request closed without merging**
