### PR TITLE
[pvr.tvh] Added support for getting and setting startExtra, stopExtra, r...

### PR DESCRIPTION
**Pull request by ksooo**
...etention, priority properties of recordings and timers.

### CODE REVIEW

**Comment by Jalle19** [comment]
Are these fields available on all versions of tvheadend or should we do some version check? @perexg ?

**Comment by Glenn-1990** [comment]
these fields are available since htsp version 13
https://github.com/tvheadend/tvheadend/pull/479/commits

**Comment by ksooo** [comment]
According to https://tvheadend.org/projects/tvheadend/wiki/Htsp and https://github.com/tvheadend/tvheadend/pull/479/commits it is as follows:

@Glenn-1990 : You should update htsp documentation (link above) with documentation for retention, the _Autorec_ stuff etc.
- For htsp method addDvrEntry, the fields priority, startExtra and stopExtra were added in version 5, retention was added in version 13
- For method updateDvrEntry, the fields startExtra and stopExtra were added in version 6, priority and retention were added in version 13

I could add respective version checks, but I'm not sure whether this is actually necessary, because older tvheadend implementations will simply ignore the unknown fields.

@perexg : what do you think?

**Comment by ksooo** [comment]
Ping! How do we want to procede?

**Comment by Jalle19** [comment]
Could you add the checks for the fields that are in v13?

**Comment by ksooo** [comment]
Sure. Will do tonight or tomorrow.

**Comment by Jalle19** [comment]
Great, thanks!

**Comment by ksooo** [comment]
Here we go. Ready for merge, if you like.

**Comment by Jalle19** [comment]
Could you still get rid of the random whitespace changes here and there? I think all the files use spaces instead of tabs. Otherwise it looks good at a glance, will merge once the whitespace is fixed.

**Comment by ksooo** [comment]
I'm not using hard tabs.

Some of the whitespace changes are replacements of some lines containing only one or two spaces followed by CR, by lines containing only a CR.

All other spaces/indentation changes are pure for readability, aligned with the pattern used in the rest of the file.

Not need for changes, IMHO. what do you think?

**Comment by Jalle19** [comment]
Sorry was hard to see from the diff on the phone.

**Pull request merged**
