### PR TITLE
[pvr.tvh] Fix: Never lock m_mutex when doing a callback to kodi. Otherwi...

### PR DESCRIPTION
**Pull request by ksooo**
Never lock m_mutex when doing a callback to Kodi. Otherwise kodi will easily deadlock!

Story: When using pvr.tvh (0.9.5) I randomly ran into deadlocks of Kodi. But no deadlocks with pvr.hts, though. All deadlocks exposed the same problem. In difference to pvr.hts, pvr.tvh holds own mutex while doing callbacks to kodi (TransferXYZ function calls). This is evil wrt. concurrency.

Example (Annoteded gdb-provided callstack): http://paste.ubuntu.com/8862842/

Note: The diff is not easily readable, but the change is straightforward: While holding the object's mutex, collect the data to be transferred back to Kodi. Then, release the mutex and transfer the collected data. Follow this common concurrency pattern for all kind of data to be transferred.

Note2: pvr.hts follows (and always did follow, afaict) this pattern and consequently does only do callbacks without object's mutex locked.

### CODE REVIEW

**Comment by Jalle19** [comment]
@adamsutton your take on this? I remember something about deadlocks when you implemented the message queue.

**Comment by Jalle19** [comment]
@ksooo I just had a look at the diff excluding white-space changes, looks good to me. I've seen some random deadlocks as well from time to time, mostly when entering the recordings window. People using Mac OS X have also had random things happen to them, hopefully this could fix some of them.

I have some small changes lined up I'd like to get pushed before doing a new release, I'll include this whenever I'm done with those (hopefully during the weekend).

**Comment by ksooo** [comment]
@Jalle19 Perfect! :-)

**Comment by ksooo** [comment]
@jalle19 just noticed 0.9.6 is out, but without this PR. ;-/ Any reason for not including it?

**Comment by Jalle19** [comment]
@ksooo sorry about that, I simply forgot. I'll do a new release this weekend.

**Comment by Jalle19** [comment]
Haven't had time to test this yet, let's hope it works! Thanks for the contribution and once again I'm sorry I forgot to include it in 0.9.6.

**Pull request merged**
